import { Injectable } from '@nestjs/common';
import { Prisma, TransactionType, WalletBalanceBucket } from '@prisma/client';

export interface LedgerReference {
  id: string;
  type: 'COMMISSION' | 'PAYOUT_REQUEST' | 'MONTHLY_BONUS' | 'ORDER_REFUND';
}

export interface LedgerBalanceChange {
  bucket: WalletBalanceBucket;
  transactionType: TransactionType;
  amount: Prisma.Decimal;
  balanceBefore: Prisma.Decimal;
  balanceAfter: Prisma.Decimal;
}

export interface StoreLedgerBalance {
  storeId: string;
  storeBalanceBefore: Prisma.Decimal;
  storeBalanceAfter: Prisma.Decimal;
}

@Injectable()
export class FinancialLedgerService {
  // Intentionally exposes only append. All callers supply their transaction client.
  appendEntry(
    tx: Prisma.TransactionClient,
    walletId: string,
    reference: LedgerReference,
    change: LedgerBalanceChange,
    storeBalance?: StoreLedgerBalance,
  ) {
    if (
      !change.amount.isFinite() ||
      !change.balanceBefore.isFinite() ||
      !change.balanceAfter.isFinite() ||
      change.amount.isZero() ||
      change.amount.decimalPlaces() > 2 ||
      !change.balanceBefore.plus(change.amount).equals(change.balanceAfter)
    ) {
      throw new Error('Financial ledger balance invariant violated');
    }
    if (
      storeBalance &&
      (!storeBalance.storeBalanceBefore.isFinite() ||
        !storeBalance.storeBalanceAfter.isFinite() ||
        !storeBalance.storeBalanceBefore
          .plus(change.amount)
          .equals(storeBalance.storeBalanceAfter))
    ) {
      throw new Error('Store ledger balance invariant violated');
    }
    return tx.financialLedger.create({
      data: {
        walletId,
        transactionType: change.transactionType,
        balanceBucket: change.bucket,
        amount: change.amount,
        balanceBefore: change.balanceBefore,
        balanceAfter: change.balanceAfter,
        referenceId: reference.id,
        referenceType: reference.type,
        ...storeBalance,
        // UUID and createdAt are generated by PostgreSQL, not client input.
      },
    });
  }
}
