import { useState, type FormEvent, type ReactNode } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, LogIn, Mail, Phone, Share2, ShieldCheck, Sparkles, Store, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import './platform.css';

type AuthRole='kol'|'shop'|'admin';

export function LoginPage(){const nav=useNavigate();const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);const[role,setRole]=useState<AuthRole>('kol');const submit=(e:FormEvent)=>{e.preventDefault();setLoading(true);const id=role==='shop'?'shop-dashboard':role==='admin'?'admin-dashboard':'kol-dashboard';window.setTimeout(()=>nav(`/app/${id}`),450)};return <AuthFrame mode="login"><h1>Chào mừng trở lại</h1><span>Chọn vai trò và đăng nhập vào không gian của bạn.</span><RoleTabs value={role} onChange={setRole} admin/><form onSubmit={submit} className="auth-original-form"><Field label="Email đăng nhập" icon={<Mail/>}><input required type="email" defaultValue="demo@scanms.vn"/></Field><Field label="Mật khẩu" icon={<LockKeyhole/>} action={<a href="#forgot">Quên mật khẩu?</a>}><input required type={show?'text':'password'} defaultValue="12345678"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></Field><label className="auth-check"><input type="checkbox" defaultChecked/> Ghi nhớ đăng nhập trên thiết bị này</label><button className="auth-gold-submit" disabled={loading}><LogIn/>{loading?'Đang xác thực…':'Đăng nhập an toàn'}<ArrowRight/></button><div className="auth-divider"><span>Hoặc đăng nhập nhanh</span></div><div className="auth-social"><button type="button">G&nbsp; Google</button><button type="button">♪&nbsp; TikTok</button></div><p className="auth-switch">Chưa có tài khoản? <Link to="/register">Đăng ký thành viên ngay →</Link></p></form></AuthFrame>}

export function RegisterPage(){const nav=useNavigate();const[role,setRole]=useState<AuthRole>('kol');const[show,setShow]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();nav(`/app/${role==='shop'?'shop-dashboard':'kol-dashboard'}`)};return <AuthFrame mode="register"><h1>Tạo tài khoản mới</h1><span>Đăng ký trở thành {role==='shop'?'Chủ Shop':'KOL / CTV'} cùng SCANMS.</span><RoleTabs value={role} onChange={setRole}/><form onSubmit={submit} className="auth-original-form auth-register-form"><Field label="Họ và tên đầy đủ" icon={<UserRound/>}><input required placeholder="VD: Trần Văn Nhật"/></Field><div className="auth-two-fields"><Field label="Email" icon={<Mail/>}><input required type="email" placeholder="name@domain.com"/></Field><Field label="Số điện thoại" icon={<Phone/>}><input required placeholder="0901 234 567"/></Field></div><Field label="Kênh mạng xã hội chính / Handle (tùy chọn)" icon={<Share2/>}><input placeholder="VD: @nhatdepmoingay"/></Field><div className="auth-channel-note"><Sparkles/><span>Có thể liên kết thêm không giới hạn các kênh khác sau đăng ký.</span></div><Field label="Mật khẩu (Tối thiểu 8 ký tự)" icon={<LockKeyhole/>}><input required minLength={8} type={show?'text':'password'} placeholder="Nhập mật khẩu an toàn…"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></Field><div className="auth-strength"><ShieldCheck/><strong>Độ mạnh mật khẩu</strong><span>Chưa nhập</span></div><Field label="Nhập lại mật khẩu" icon={<LockKeyhole/>}><input required minLength={8} type="password" placeholder="Nhập lại chính xác mật khẩu trên…"/></Field><label className="auth-policy"><input required type="checkbox"/> Tôi xác nhận đã đọc và đồng ý với các quy định hoạt động của SCANMS</label><button className="auth-teal-submit"><UserRound/>Đăng ký tài khoản {role==='shop'?'Chủ Shop':'KOL / CTV'}</button><p className="auth-switch">Đã có tài khoản? <Link to="/login">Đăng nhập ngay →</Link></p></form></AuthFrame>}

function RoleTabs({value,onChange,admin=false}:{value:AuthRole;onChange:(r:AuthRole)=>void;admin?:boolean}){return <div className={`auth-original-tabs ${admin?'three':''}`}><button className={value==='kol'?'active':''} onClick={()=>onChange('kol')}><Sparkles/>KOL / CTV</button><button className={value==='shop'?'active':''} onClick={()=>onChange('shop')}><Store/>Chủ Shop</button>{admin&&<button className={value==='admin'?'active':''} onClick={()=>onChange('admin')}><ShieldCheck/>Quản trị Sàn</button>}</div>}
function Field({label,icon,action,children}:{label:string;icon:ReactNode;action?:ReactNode;children:ReactNode}){return <label className="auth-field"><span>{icon}{label}{action}</span><div>{children}</div></label>}
function AuthFrame({mode,children}:{mode:'login'|'register';children:ReactNode}){return <main className={`auth-latest-page ${mode}`}><Link to="/" className="auth-latest-logo"><span>S</span><div><strong>SCANMS</strong><small>HỆ THỐNG QUẢN LÝ MẠNG LƯỚI CTV & TIẾP THỊ</small></div></Link><section className="auth-latest-visual" aria-label={mode==='login'?'Kết nối cộng tác viên, kiến tạo doanh thu bền vững':'Khởi tạo tài khoản SCANMS'}>{mode==='register'&&<><div className="auth-register-copy"><p>Cùng SCANMS phát triển</p><h2>Mở rộng cơ hội.<br/>Tăng trưởng bền vững.</h2><span>Một tài khoản để quản lý nội dung, doanh số và thu nhập affiliate.</span></div><img src="/reference/assets/register-gold-phone-transparent.png" alt="Ứng dụng SCANMS trên điện thoại"/></>}</section><section className="auth-original-panel"><div>{children}</div></section><footer><span>Dễ dàng bắt đầu</span><span>Linh hoạt mở rộng</span><span>Cộng đồng năng động</span><span>Hỗ trợ 24/7</span></footer></main>}
