import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  InternalServerErrorException,
  Logger,
  NotFoundException,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { OrderStatus } from '@prisma/client';
import { PayOS, type Webhook } from '@payos/node';
import { randomBytes } from 'crypto';
import { PrismaService } from '../../core/database/prisma.service';

type PayosDetails = {
  orderCode: number;
  paymentLinkId?: string;
  checkoutUrl?: string;
  qrCode?: string;
  bin?: string;
  accountNumber?: string;
  accountName?: string;
  amount?: number;
};

@Injectable()
export class PayosPaymentService {
  private readonly logger = new Logger(PayosPaymentService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  private client(): PayOS {
    const clientId = this.config.get<string>('PAYOS_CLIENT_ID')?.trim();
    const apiKey = this.config.get<string>('PAYOS_API_KEY')?.trim();
    const checksumKey = this.config.get<string>('PAYOS_CHECKSUM_KEY')?.trim();
    if (!clientId || !apiKey || !checksumKey) {
      throw new ServiceUnavailableException(
        'PayOS chưa được cấu hình. Vui lòng liên hệ quản trị viên.',
      );
    }
    return new PayOS({
      clientId,
      apiKey,
      checksumKey,
      timeout: 10000,
      maxRetries: 1,
    });
  }

  private storefrontBaseUrl(): string {
    const configured = this.config.get<string>('PAYOS_STOREFRONT_URL');
    if (!configured && this.config.get<string>('NODE_ENV') === 'production') {
      throw new InternalServerErrorException(
        'PAYOS_STOREFRONT_URL chưa được cấu hình cho production',
      );
    }
    let url: URL;
    try {
      url = new URL(configured || 'http://localhost:5173');
    } catch {
      throw new InternalServerErrorException(
        'PAYOS_STOREFRONT_URL không hợp lệ',
      );
    }
    const isLocalDev =
      this.config.get<string>('NODE_ENV') !== 'production' &&
      ['localhost', '127.0.0.1'].includes(url.hostname);
    if (
      (url.protocol !== 'https:' &&
        !(isLocalDev && url.protocol === 'http:')) ||
      url.username ||
      url.password
    ) {
      throw new InternalServerErrorException(
        'PAYOS_STOREFRONT_URL phải là HTTPS (hoặc localhost khi phát triển)',
      );
    }
    return url.origin;
  }

  private webhookUrl(): string {
    const configured = this.config.get<string>('PAYOS_WEBHOOK_URL')?.trim();
    if (!configured) {
      throw new ServiceUnavailableException(
        'PayOS chưa có webhook HTTPS công khai để xác nhận thanh toán',
      );
    }
    let url: URL;
    try {
      url = new URL(configured);
    } catch {
      throw new InternalServerErrorException('PAYOS_WEBHOOK_URL không hợp lệ');
    }
    if (
      url.protocol !== 'https:' ||
      url.username ||
      url.password ||
      url.search ||
      url.hash ||
      !url.pathname.endsWith('/api/orders/payos/webhook') ||
      ['localhost', '127.0.0.1'].includes(url.hostname)
    ) {
      throw new InternalServerErrorException(
        'PAYOS_WEBHOOK_URL phải là URL HTTPS công khai của /api/orders/payos/webhook',
      );
    }
    return url.toString();
  }

  assertReady(): void {
    this.client();
    this.storefrontBaseUrl();
    this.webhookUrl();
  }

  isAvailable(): { available: boolean } {
    try {
      this.assertReady();
      return { available: true };
    } catch {
      return { available: false };
    }
  }

  private numericCode(orderId: string): number {
    // Stable positive integer under Number.MAX_SAFE_INTEGER; UUID is generated by the database.
    return Number.parseInt(orderId.replace(/-/g, '').slice(0, 12), 16) + 1;
  }

  newPaymentOrderCode(): number {
    return Number.parseInt(randomBytes(6).toString('hex'), 16) + 1;
  }

  async cancelPendingLinkForLivePriceReset(orderId: string): Promise<boolean> {
    const order = await this.prisma.order.findUnique({
      where: { id: orderId },
      select: { rawPayload: true },
    });
    const raw = (order?.rawPayload || {}) as Record<string, any>;
    if (raw.paymentStatus === 'PAID') return false;
    if (raw.paymentMethod !== 'PAYOS') return true;

    const details = raw.payos as PayosDetails | undefined;
    if (!details?.paymentLinkId && !details?.orderCode) return true;

    try {
      const payos = this.client();
      const link = details.paymentLinkId
        ? await payos.paymentRequests.cancel(
            details.paymentLinkId,
            'Livestream ended; the unpaid order was repriced.',
          )
        : await payos.paymentRequests.cancel(
            details.orderCode,
            'Livestream ended; the unpaid order was repriced.',
          );
      return link.status === 'CANCELLED' || link.status === 'EXPIRED';
    } catch (error) {
      this.logger.warn(
        `Could not cancel PayOS link before repricing order ${orderId}: ${error instanceof Error ? error.message : String(error)}`,
      );
      return false;
    }
  }

  private async ownedOrder(publicCode: string, userId: string) {
    const order = await this.prisma.order.findFirst({
      where: {
        externalOrderSn: publicCode,
        customerId: userId,
        sourcePlatform: 'INTERNAL',
      },
    });
    if (!order) throw new NotFoundException('Không tìm thấy đơn hàng của bạn');
    const raw = (order.rawPayload || {}) as Record<string, any>;
    if (raw.paymentMethod !== 'PAYOS') {
      throw new BadRequestException('Đơn hàng này không chọn thanh toán PayOS');
    }
    return { order, raw };
  }

  async createLink(publicCode: string, userId: string) {
    this.assertReady();
    const payos = this.client();
    const { order, raw } = await this.ownedOrder(publicCode, userId);
    if (order.status === OrderStatus.CANCELLED)
      throw new BadRequestException('Đơn hàng đã hủy');
    if (raw.paymentStatus === 'PAID')
      throw new ConflictException('Đơn hàng đã thanh toán');
    const amount = Number(order.finalAmount);
    if (!Number.isSafeInteger(amount) || amount <= 0) {
      throw new BadRequestException(
        'Số tiền thanh toán PayOS phải là số nguyên VND dương',
      );
    }
    let existing = raw.payos as PayosDetails | undefined;
    if (
      existing?.checkoutUrl &&
      existing.qrCode &&
      existing.amount === amount
    ) {
      return { ...existing, paymentStatus: raw.paymentStatus };
    }
    let orderCode = existing?.orderCode || this.numericCode(order.id);
    if (existing?.paymentLinkId && existing.amount !== amount) {
      const cancelled = await this.cancelPendingLinkForLivePriceReset(order.id);
      if (!cancelled) {
        throw new ConflictException(
          'Liên kết thanh toán cũ đang được xử lý. Vui lòng tải lại sau ít phút.',
        );
      }
      orderCode = this.newPaymentOrderCode();
      existing = undefined;
      await this.prisma.order.update({
        where: { id: order.id },
        data: { rawPayload: { ...raw, payos: { orderCode } } },
      });
    }
    const base = this.storefrontBaseUrl();
    const resultPath = `/payment/payos-return?order=${encodeURIComponent(publicCode)}`;
    const returnUrl = `${base}${resultPath}`;
    const cancelUrl = `${base}${resultPath}&cancelled=1`;

    // Store the deterministic numeric code before calling PayOS so an early webhook can locate the order.
    if (!existing?.orderCode) {
      await this.prisma.order.update({
        where: { id: order.id },
        data: { rawPayload: { ...raw, payos: { orderCode } } },
      });
    }

    let link;
    try {
      link = await payos.paymentRequests.create({
        orderCode,
        amount,
        description: `SM${orderCode.toString(36).toUpperCase().slice(-7)}`,
        returnUrl,
        cancelUrl,
      });
    } catch (error) {
      this.logger.error(
        `PayOS link creation failed for order ${publicCode}: ${error instanceof Error ? error.message : String(error)}`,
      );
      throw new ServiceUnavailableException(
        'Chưa tạo được mã PayOS. Đơn đã được ghi nhận; vui lòng thử tạo mã lại.',
      );
    }

    if (
      link.orderCode !== orderCode ||
      link.amount !== amount ||
      !link.qrCode ||
      !link.checkoutUrl.startsWith('https://pay.payos.vn/')
    ) {
      throw new ServiceUnavailableException(
        'PayOS trả về thông tin thanh toán không hợp lệ',
      );
    }
    const details: PayosDetails = {
      orderCode,
      paymentLinkId: link.paymentLinkId,
      checkoutUrl: link.checkoutUrl,
      qrCode: link.qrCode,
      bin: link.bin,
      accountNumber: link.accountNumber,
      accountName: link.accountName,
      amount,
    };
    const paymentStatus = await this.prisma.$transaction(async (tx) => {
      const rows = await tx.$queryRaw<Array<{ raw_payload: any }>>`
        SELECT raw_payload FROM orders WHERE id = ${order.id}::uuid FOR UPDATE
      `;
      const latest = (rows[0]?.raw_payload || {}) as Record<string, any>;
      await tx.order.update({
        where: { id: order.id },
        data: {
          rawPayload: {
            ...latest,
            payos: { ...(latest.payos || {}), ...details },
          },
        },
      });
      return latest.paymentStatus || 'WAITING_PAYMENT';
    });
    return { ...details, paymentStatus };
  }

  async getStatus(publicCode: string, userId: string) {
    const { order, raw } = await this.ownedOrder(publicCode, userId);
    return {
      publicOrderCode: order.externalOrderSn,
      paymentStatus: raw.paymentStatus || 'WAITING_PAYMENT',
      orderStatus: order.status,
      checkoutUrl: raw.payos?.checkoutUrl || null,
    };
  }

  async handleWebhook(body: Webhook) {
    let data;
    try {
      data = await this.client().webhooks.verify(body);
    } catch {
      throw new ForbiddenException('Chữ ký webhook PayOS không hợp lệ');
    }
    if (!body.success || body.code !== '00' || data.code !== '00') {
      return { success: true };
    }
    if (
      !Number.isSafeInteger(data.orderCode) ||
      !Number.isSafeInteger(data.amount) ||
      data.amount <= 0 ||
      data.currency !== 'VND' ||
      !data.reference
    ) {
      throw new BadRequestException('Dữ liệu thanh toán PayOS không hợp lệ');
    }

    return this.prisma.$transaction(async (tx) => {
      const rows = await tx.$queryRaw<
        Array<{
          id: string;
          external_order_sn: string;
          status: OrderStatus;
          final_amount: unknown;
          raw_payload: any;
        }>
      >`
        SELECT id, external_order_sn, status, final_amount, raw_payload
        FROM orders
        WHERE raw_payload->'payos'->>'orderCode' = ${String(data.orderCode)}
        FOR UPDATE
      `;
      const order = rows[0];
      if (!order) {
        // PayOS sends a signed sample webhook when registering the endpoint.
        this.logger.warn(
          `PayOS webhook order code ${data.orderCode} does not match a SCANMS order`,
        );
        return { success: true };
      }
      const raw = (order.raw_payload || {}) as Record<string, any>;
      if (
        raw.paymentMethod !== 'PAYOS' ||
        Number(order.final_amount) !== data.amount ||
        (raw.payos?.paymentLinkId &&
          raw.payos.paymentLinkId !== data.paymentLinkId)
      ) {
        throw new BadRequestException('Giao dịch PayOS không khớp đơn hàng');
      }
      const transactionId = `PAYOS:${data.reference}`;
      if (raw.paymentStatus === 'PAID') {
        if (raw.transactionId === transactionId) return { success: true };
        throw new ConflictException(
          'Đơn hàng đã được thanh toán bởi giao dịch khác',
        );
      }
      if (order.status === OrderStatus.CANCELLED) {
        throw new ConflictException(
          'Đơn đã hủy nhưng PayOS báo thanh toán; cần đối soát thủ công',
        );
      }
      await tx.paymentTransaction.create({
        data: {
          orderId: order.id,
          transactionId,
          amount: data.amount,
          currency: 'VND',
          paymentMethod: 'PAYOS',
          status: 'SUCCESS',
        },
      });
      await tx.order.update({
        where: { id: order.id },
        data: {
          rawPayload: {
            ...raw,
            paymentStatus: 'PAID',
            transactionId,
            paidAt: new Date().toISOString(),
            payos: { ...(raw.payos || {}), paymentLinkId: data.paymentLinkId },
          },
          sourceUpdatedAt: new Date(),
        },
      });
      await tx.auditLog.create({
        data: {
          action: 'PAYMENT_RECONCILED',
          details: {
            provider: 'PAYOS',
            orderCode: order.external_order_sn,
            transactionId,
            amount: data.amount,
          },
        },
      });
      this.logger.log(
        `PayOS payment confirmed for order ${order.external_order_sn}`,
      );
      return { success: true };
    });
  }
}
